### ISSUE TITLE
Multiple categories for Blog post

### ISSUE THREAD

**Issue by reypm** [pyrocms/pyrocms#2747]
I wish I could select more than one category for each blog post, right now I can only have one post in one category

**Comment by numerogeek** [comment]
Hi guys !

this debate is pretty interesting, even if I agree with Phil.
a blog post with multiple categories could be pretty bad for your SEO (if
you put the category in the URL, you may have 2 different URL for the same
content.)

But :

I've developped a module Categories. The purpose is mainly to help
developpers :
Instead of developping a categories system each time you need it, I made a
"core" module :
So you call the API, create a new instance; it automatically offer you a
full categories manager. (add, edit, delete, drag & drop ordering,
mutliselect possible..)

https://github.com/bergeo-fr/Categories

@Phil Let me know what you think about it, and it's free. it can save a lot
of times to developpers.

On Thu, May 16, 2013 at 3:32 PM, Phil Sturgeon notifications@github.comwrote:

> Right, or "handsets" or "reviews".
> 
> Sent from my iPhone
> 
> On May 16, 2013, at 2:50 AM, Marco Grüter notifications@github.com
> wrote:
> 
> > usually you would do something like that by having a category 'mobile'
> > and then tag the android and samsung specific posts
> > 
> > check out other big blog sites, almost all have a really small amount of
> > categories (if any at all) but lots of tags
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pyrocms/pyrocms/issues/2747#issuecomment-18001038
> .

##
