### ISSUE TITLE
Keywords on Blog Module

### ISSUE THREAD

**Issue by deibioctavio** [pyrocms/pyrocms#2874]
This error is being displaying when i create a blog and add keywords on a keywords section into blog->settings and i try to add the blog module to a page

---

A PHP Error was encountered

Severity: Notice

Message: Array to string conversion

Filename: Lex/Parser.php
## Line Number: 190

I found the error on into _process_post method blog/controllers/post.php file.

---

foreach ($keywords as $key)
{
 $formatted_keywords[]  = array('keyword' => $key->name);
 $keywords_arr[]        = $key->name;

**Comment by sonirico** [comment]
Hi there, sorry for replying in a closed thread. Indeed, it's a bug and it's still present, since I have the 2.2 version and the same problem. As I suspected, the code  posted by  @CameronGilroy is deprecated. Just change it to:

```
{{ keywords }}
    {{ if is_first }}
    <h3>{{ total }} Keywords</h3>
    <ol>
    {{ endif }}
        <li><a href="/tagged/{{ keyword }}">{{ keyword }}</a></li>
    {{ if is_last }}
    </ol>
    {{ endif }}
{{ /keywords }}
``` 
So the problem solves itself by iterating over each keyword. Hope this help. Anyway it seems that pyrocms is walking towards death, as his father CodeIgniter. I recommend just check out other frameworks as Laravel (PHP) or Django (Python). There are other content management systems for them.

**Comment by jerel** [comment]
@sonirico PyroCMS 3.0 is on Laravel, not CodeIgniter https://www.pyrocms.com/blog/2015/01/release-pyrocms-30-alpha1

**Comment by sonirico** [comment]
Great news, but I am unable to find that reference in the article you shared.

**Comment by jerel** [comment]
It's mentioned here https://www.pyrocms.com/blog/2014/11/pyrocms-30-progress-and-launch or take a look at the repo which is obviously Laravel https://github.com/pyrocms/pyrocms

**Comment by RyanThompson** [comment]
Yep, @sonirico death has been avoided.
