### ISSUE TITLE
Not working some template plugins

### ISSUE THREAD

**Issue by armoni** [pyrocms/pyrocms#3268]
{{ template:set_title value="title" }}
{{ template:set_metadata name="description" value="description" type="meta" }}
{{ template:set_breadcrumb name="Page" uri="page" reset="true" }}

I found a solution for {{ template:set_title }}. But it should be location before {{ template:title }}. it doesn't seem possible that use to streams module and want to be SEO.

My solution for set_title:
public function set_title()
{
   $value = $this->attribute('value');
   $data = & $this->load->_ci_cached_vars;
   $data['template']['title'] = implode(' | ', explode(',', $value));
}

Does not seem useful?

**Comment by huglester** [comment]
@RyanThompson  I think @armoni is right?

@armoni can you send a PR ?

**Comment by RyanThompson** [comment]
If you are using the streams API then set it in your controller before your view is even hit. 

If you are using the streams module I would spin up a quick plugin that would modify the template object if possible - otherwise an event might be in order like "onRendering"..

Reopen if this is something you want to explore or have a PR to check out!
