### ISSUE TITLE
Unable to open Multisite Manager for my site

### ISSUE THREAD

**Issue by techsandeep** [pyrocms/pyrocms#3441]
Hi Team,
I have purchased pyrocms pro for one of my site http://www.mydomain.com but I am unable to open my multisite manager on this domain by typing http://www.mydomain.com/sites. its show 404  error. I want to add one more site in the same DB with different tables.

**Comment by marcogrueter** [comment]
I've got this problems a few times, and 100% of those times it was because the domain name I've accessed the site with didn't match the domain name in 'core_sites'. Most of the time, I've developed on 'site.local' and the site was published as 'www.site.local'.

So check your entries in the 'core_sites' table.

**Comment by techsandeep** [comment]
Fined The Solution. Just update my main domain name in core_sites table. You can login in Multisite manager by only email and password you setuped during installation of site not by admin password after changing it.
