### ISSUE TITLE
[3.0] composer update : missing Anomaly\Streams\Platform\Model\Settings\SettingsSettingsEntryModel

### ISSUE THREAD

**Issue by remyma** [pyrocms/pyrocms#3457]
Hi,

After composer update, I'm unable to build cause missing class : 
`
use Anomaly\Streams\Platform\Model\Settings\SettingsSettingsEntryModel;
`

Maybe you forgot to commit something on streams-platform ?

**Comment by RyanThompson** [comment]
The module should be in there - but pull that module to update it depending on when it was. I removed the code causing that issue a bit ago.


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by remyma** [comment]
Ok After a new freh install

**Comment by jhubb81** [comment]
I've done a fresh install of the latest version after pulling today and am getting this issue on "php artisan clear-compiled"

[Symfony\Component\Debug\Exception\FatalErrorException]                    
  Class 'Anomaly\Streams\Platform\Model\Settings\SettingsSettingsEntryModel  
  ' not found

and the same when I browse to the app:

[10-Mar-2015 11:35:39 Europe/London] PHP Fatal error:  Class 'Anomaly\Streams\Platform\Model\Settings\SettingsSettingsEntryModel' not found in /Users/johnhubbard/Sites/pyrocms/3.0-dev/core/anomaly/settings-module/src/Setting/SettingModel.php on line 14

**Comment by RyanThompson** [comment]
Try pulling down the example theme if you have it.

Otherwise composer update and make sure everything is up to date. That should not be triggered in the current build.

On Mar 10, 2015, at 7:39 AM, jhubb81 <notifications@github.com<mailto:notifications@github.com>> wrote:


I've done a fresh install of the latest version after pulling today and am getting this issue on "php artisan clear-compiled"

[Symfony\Component\Debug\Exception\FatalErrorException]

Class 'Anomaly\Streams\Platform\Model\Settings\SettingsSettingsEntryModel

' not found

and the same when I browse to the app:

[10-Mar-2015 11:35:39 Europe/London] PHP Fatal error: Class 'Anomaly\Streams\Platform\Model\Settings\SettingsSettingsEntryModel' not found in /Users/johnhubbard/Sites/pyrocms/3.0-dev/core/anomaly/settings-module/src/Setting/SettingModel.php on line 14

**Comment by jhubb81** [comment]
Where do I pull the example theme into?


On 10 March 2015 at 16:08:50, Ryan Thompson (notifications@github.com) wrote:

Try pulling down the example theme if you have it.

Otherwise composer update and make sure everything is up to date. That should not be triggered in the current build.

On Mar 10, 2015, at 7:39 AM, jhubb81 <notifications@github.com<mailto:notifications@github.com>> wrote:


I've done a fresh install of the latest version after pulling today and am getting this issue on "php artisan clear-compiled"

[Symfony\Component\Debug\Exception\FatalErrorException]

Class 'Anomaly\Streams\Platform\Model\Settings\SettingsSettingsEntryModel

' not found

and the same when I browse to the app:

[10-Mar-2015 11:35:39 Europe/London] PHP Fatal error: Class 'Anomaly\Streams\Platform\Model\Settings\SettingsSettingsEntryModel' not found in /Users/johnhubbard/Sites/pyrocms/3.0-dev/core/anomaly/settings-module/src/Setting/SettingModel.php on line 14

**Comment by RyanThompson** [comment]
You can put it in any of the following:

core/anomaly
addons/shared/anomaly
addons/REF/anomaly (likely REF = default)

On Mar 10, 2015, at 4:25 PM, jhubb81 <notifications@github.com<mailto:notifications@github.com>> wrote:

Where do I pull the example theme into?


On 10 March 2015 at 16:08:50, Ryan Thompson (notifications@github.com<mailto:notifications@github.com>) wrote:

Try pulling down the example theme if you have it.

Otherwise composer update and make sure everything is up to date. That should not be triggered in the current build.

On Mar 10, 2015, at 7:39 AM, jhubb81 <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


I've done a fresh install of the latest version after pulling today and am getting this issue on "php artisan clear-compiled"

[Symfony\Component\Debug\Exception\FatalErrorException]

Class 'Anomaly\Streams\Platform\Model\Settings\SettingsSettingsEntryModel

' not found

and the same when I browse to the app:

[10-Mar-2015 11:35:39 Europe/London] PHP Fatal error: Class 'Anomaly\Streams\Platform\Model\Settings\SettingsSettingsEntryModel' not found in /Users/johnhubbard/Sites/pyrocms/3.0-dev/core/anomaly/settings-module/src/Setting/SettingModel.php on line 14

**Comment by jhubb81** [comment]
OK, I’ll take a look. I did a total re-install and everything worked well. There must have been some old composer files hanging around on the old one that weren’t being deleted when I reset the repo.

Thanks,

John


On 11 March 2015 at 18:18:03, Ryan Thompson (notifications@github.com) wrote:

You can put it in any of the following:

core/anomaly
addons/shared/anomaly
addons/REF/anomaly (likely REF = default)

On Mar 10, 2015, at 4:25 PM, jhubb81 <notifications@github.com<mailto:notifications@github.com>> wrote:

Where do I pull the example theme into?


On 10 March 2015 at 16:08:50, Ryan Thompson (notifications@github.com<mailto:notifications@github.com>) wrote:

Try pulling down the example theme if you have it.

Otherwise composer update and make sure everything is up to date. That should not be triggered in the current build.

On Mar 10, 2015, at 7:39 AM, jhubb81 <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


I've done a fresh install of the latest version after pulling today and am getting this issue on "php artisan clear-compiled"

[Symfony\Component\Debug\Exception\FatalErrorException]

Class 'Anomaly\Streams\Platform\Model\Settings\SettingsSettingsEntryModel

' not found

and the same when I browse to the app:

[10-Mar-2015 11:35:39 Europe/London] PHP Fatal error: Class 'Anomaly\Streams\Platform\Model\Settings\SettingsSettingsEntryModel' not found in /Users/johnhubbard/Sites/pyrocms/3.0-dev/core/anomaly/settings-module/src/Setting/SettingModel.php on line 14
