### ISSUE TITLE
How jump the installer step and configure database and admin manually

### ISSUE THREAD

**Issue by valle6** [pyrocms/pyrocms#3493]
During installation of PyroCMS 3, access to url domain/projects/dev/pyrocms/public/index.php/installer  causes errors:
module::message.database_error
There is a database configuration error.

Debug Exceptions:
Cannot add listen to Queries for Laravel Debugbar: SQLSTATE[42000] [1044] Access denied for user ''@'localhost' to database 'streams'/var/www/projects/dev/pyrocms/vendor/barryvdh/laravel-debugbar/src/LaravelDebugBar.php#306Exception
SQLSTATE[42000] [1044] Access denied for user ''@'localhost' to database 'streams'/var/www/projects/dev/pyrocms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php#47

The database used is PostgreSQL 9.1. I've tried several users and changed privileges. The PostgreSQL is in the same machine and is configured to receive TCP-IP requests (http://www.postgresql.org/docs/9.1/static/errcodes-appendix.html). This database is used without problems in others projects, based in Symfony and Laravel (OctoberCMS). The file permissions is:
chmod -R 775 pyrocms; chgrp -R www-data pyrocms;

I think that the easier solution would be jump this installer page and make manually configuration of database and admin user. How disable the installer step (run installer)? There are others actions executed by this step?

**Comment by RyanThompson** [comment]
After you submit the install form an .env file is generated in your root directory. You can mark that as installed=false and just hit the URI "installer/install" and it will use that file.

**Comment by RyanThompson** [comment]
I'll have to look into the db issue if any though not sure what's going on there..

**Comment by valle6** [comment]
Thank you for the tip. 

I've followed the instructions and managed to install. I've created manually the file .env and accessed the link "http://domain.biz/projects/dev/pyrocms/public/index.php/installer/install". The install has occurred completely.  See file .env bellow:


INSTALLED=true
APP_DEBUG=true
APP_ENV=local
APP_KEY= str_random(32)
DB_DRIVER=pgsql
DB_HOST=localhost
DB_DATABASE=pyrocms
DB_USERNAME=developer
DB_PASSWORD=password
APPLICATION_NAME=Default
APPLICATION_DOMAIN=domain.biz/projects/dev/pyrocms
APPLICATION_REFERENCE=default
CACHE_DRIVER=file
SESSION_DRIVER=file
ADMIN_THEME=anomaly.theme.anomaly
STANDARD_THEME=anomaly.theme.anomaly
LOCALE=en
TIMEZONE=UTC
MAIL_DRIVER=mail
SMTP_HOST=null
SMTP_PORT= null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME=null
SMTP_USERNAME=null
SMTP_PASSWORD=null
MAIL_DEBUG=false
ADMIN_USERNAME=admin
ADMIN_EMAIL=mail@gmail.com
ADMIN_PASSWORD=password


Problems
The link "New Site" of the dashboard (http://domain.biz/projects/dev/pyrocms/public/index.php) has problem, producing an error. See urls and results

- http://domain.biz/projects/dev/pyrocms/public/index.php/admin/
If there is session : redirect to login page. 
Without session: redirect to dashboard page (http://domain.biz/projects/dev/pyrocms/public/index.php/admin/dashboard).

- http://domain.biz/projects/dev/pyrocms/public/index.php/admin/login
Login page

- http://domain.biz/projects/dev/pyrocms/public/index.php/admin/dashboard
It works.

- http://domain.biz/projects/dev/pyrocms/public/index.php/
Redirect to http://domain.biz/index.php

- Link "New site" - ERROR
http://domain.biz/projects/dev/pyrocms/public/
http://domain.biz/projects/dev/pyrocms/public
http://domain.biz/projects/dev/pyrocms/public/index.php
PRODUCES ERROR:
NotFoundHttpException in RouteCollection.php line 145:

Suggestion
I think the no creation of .env file and the error of the link "See Sites" pehaps derives of install Pyro in subfolders. 
I suggest capture the error and generate enlightening error message, during creation of .env file, and correct "New Site" route. 

Please, verify the file Anomaly\InstallerModule\Form\nstallerFormFields. I think the options key must be compatible with "database connection name" in config/database.php file. The Postgres key should have "pgsql", shouldn't  it?

...
'config'       => [
             'options' => [
                    'mysql'    => 'MySQL',
                     'pgsql' => 'Postgres', //'postgres' => 'Postgres',
                      'sqlite'   => 'SQLite',
                      'sqlsrv'   => 'SQL Server',
              ]
 ],
...

Regards.

**Comment by RyanThompson** [comment]
Try simply changing some of your routing. Because you're routing is technically incorrect, admin stuff is not correctly determined.

Your web root should be root/public it seems you have it at just root/

This is a laravel thing and is actually pretty cool. It let's you keep all your system / architecture stuff out of public access!

Let me know if this helps you out with some of these ^_^

On Jun 14, 2015, at 12:52 PM, Henrique <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for the tip.

I've followed the instructions and managed to install. I've created manually the file .env and accessed the link "http://domain.biz/projects/dev/pyrocms/public/index.php/installer/install". The install has occurred completely. See file .env bellow:

INSTALLED=true
APP_DEBUG=true
APP_ENV=local
APP_KEY= str_random(32)
DB_DRIVER=pgsql
DB_HOST=localhost
DB_DATABASE=pyrocms
DB_USERNAME=developer
DB_PASSWORD=password
APPLICATION_NAME=Default
APPLICATION_DOMAIN=domain.biz/projects/dev/pyrocms
APPLICATION_REFERENCE=default
CACHE_DRIVER=file
SESSION_DRIVER=file
ADMIN_THEME=anomaly.theme.anomaly
STANDARD_THEME=anomaly.theme.anomaly
LOCALE=en
TIMEZONE=UTC
MAIL_DRIVER=mail
SMTP_HOST=null
SMTP_PORT= null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME=null
SMTP_USERNAME=null
SMTP_PASSWORD=null
MAIL_DEBUG=false
ADMIN_USERNAME=admin
ADMIN_EMAIL=mail@gmail.com<mailto:mail@gmail.com>
ADMIN_PASSWORD=password

Problems
The link "New Site" of the dashboard (http://domain.biz/projects/dev/pyrocms/public/index.php) has problem, producing an error. See urls and results

  *   http://domain.biz/projects/dev/pyrocms/public/index.php/admin/
If there is session : redirect to login page.
Without session: redirect to dashboard page (http://domain.biz/projects/dev/pyrocms/public/index.php/admin/dashboard).

  *   http://domain.biz/projects/dev/pyrocms/public/index.php/admin/login
Login page

  *   http://domain.biz/projects/dev/pyrocms/public/index.php/admin/dashboard
It works.

  *   http://domain.biz/projects/dev/pyrocms/public/index.php/
Redirect to http://domain.biz/index.php

  *   Link "New site" - ERROR
http://domain.biz/projects/dev/pyrocms/public/
http://domain.biz/projects/dev/pyrocms/public
http://domain.biz/projects/dev/pyrocms/public/index.php
PRODUCES ERROR:
NotFoundHttpException in RouteCollection.php line 145:

Suggestion
I think the no creation of .env file and the error of the link "See Sites" pehaps derives of install Pyro in subfolders.
I suggest capture the error and generate enlightening error message, during creation of .env file, and correct "New Site" route.

Please, verify the file Anomaly\InstallerModule\Form\nstallerFormFields. I think the options key must be compatible with "database connection name" in config/database.php file. The Postgres key should have "pgsql", shouldn't it?

...
'config' => [
'options' => [
'mysql' => 'MySQL',
'pgsql' => 'Postgres', //'postgres' => 'Postgres',
'sqlite' => 'SQLite',
'sqlsrv' => 'SQL Server',
]
],
...

Regards.

**Comment by huglester** [comment]
@valle6  did you solve it?

**Comment by RyanThompson** [comment]
Closing this for now - will have CLI installer soon enough anyways.
