### ISSUE TITLE
Artisan DB Commands Not Available If DB Not Already Set Up

### ISSUE THREAD

**Issue by danhunsaker** [pyrocms/pyrocms#3526]
The current design of PyroCMS seems to rely on running the installer for every deployment at least once, or at least migrating DB contents across manually from an initial deployment to subsequent ones.  I can't run migrations until the database is already set up, which feels more than counter-intuitive, especially when the installer doesn't even actually run the migrations itself (or, well, at least doesn't record their run in the migrations table), causing them to fail on key constraints when run later to pull in updates.

I deploy sites by pushing code to a server, which then automatically checks it out and runs a few maintenance commands (`composer update`, `artisan migrate`, and the like) before making it available to the web server.  Schema changes are kept in migrations, rather than SQL files, and data changes are shipped in seeds, as Laravel encourages.  This approach has worked well in the past, even in previous versions of Pyro built on CodeIgniter, so I'm surprised it isn't valid now.

I suppose my real question is, if this is desired behavior, what is the recommended approach to automating new deployments of existing sites (such as the move from local dev into production)?

**Comment by RyanThompson** [comment]
Hey there! Thanks for the input - a couple things though:

1.) Pull latest and try installing again. I was an idiot and pushed a change last night that caused installer to NOT install addons. See https://github.com/anomalylabs/streams-platform/commit/b5b569f4d17ab4d7abad06f1751ed477d27e4019 (silly, I know).

2.) Granted, you can NOT install the system without running the installer, I am working this weekend to finally finalize the installer. One of the features / changes is making the installer a.) 100% command driven and b.) event generated

So adding your own custom hooks to the installer for installation will be easy and deploying a headless install via a script / service will be easier since you will then be able to install with the CLI if you desire.

That said, all addons / streams rely entirely on migrations (they all have their own migrations folder) which has a short syntax for setting up streams, fields and assignments and can handle normal migrations too of course.

Seeders are also supported through `php artisan db:seed --addon=vendor.addon_type.slug`

This will look for the seeder in the same namespace as a module:

    ExampleModule // the module / addon class
    ExampleModuleSeeder // the associated seeder

From there you can run `$this->call(SeederClass::class);` as many times as you want to populate your data.

**Comment by danhunsaker** [comment]
The installer seems to be running fine.  I've already run it locally, prior to the changes last night.  I was just hoping to avoid having to re-run it again when I deploy to production, because the idea is to remove the installer folder once it's been run...

**Comment by RyanThompson** [comment]
You can run `rm -Rf core/anomaly/installer-module` after you deploy and it installs itself right?

I can add an `addon:delete` command too.

**Comment by danhunsaker** [comment]
I can.  I just already had it removed locally so the dashboard would quit complaining about it in development, so it never got committed to the repo.

**Comment by RyanThompson** [comment]
In your local dev - you can set your `.env` file to `APP_DEBUG=false` and it should leave you alone - if it doesn't it, should and there's a small issue.

**Comment by danhunsaker** [comment]
That feels a tad backwards...  I'd expect the warning to be present in production mode, since that's the version most at risk from leaving it.  Development mode should care a bit less.

Of course, I removed the installer module dependency from my `composer.json`, too, because `composer update` kept bringing it back.  Adding that back in would take care of not having it on deploy...

**Comment by RyanThompson** [comment]
Sorry - scratch that and reverse it ^_^ (drinking wine)

`APP_DEBUG=true` removes the warning.
