### ISSUE TITLE
belongsToMany field-type for TableBuilder fails

### ISSUE THREAD

**Issue by liviumalvin** [pyrocms/pyrocms#3530]
If a stream contains a field-type which imposes a belongsToMany relation type (e.g anomaly.field_type.multiple ) and the stream is presented by a TableBuilder , an error will occur when the field will be presented; 

 `FatalErrorException in ColumnValue.php line 88:
Call to undefined method Anomaly\Streams\Platform\Entry\EntryCollection::getTitle()`

This happens because of the fact that `$relation` is not an `EntryModel` , but an `EntryCollection`, so that might be considered an edge-case.

**Comment by RyanThompson** [comment]
This is not the issue - the issue is that in tables, unless you decorate the data into a comma delimited string, it EXPECTS you to refer to one object. Not a collection. You need to either make a presenter method on the entry and reference it OR use something like a closure to loop the entry value and return a string for the table.
