### ISSUE TITLE
[3.0-beta2] Artisan migration compliance in PyroCMS?

### ISSUE THREAD

**Issue by uxinnuendo** [pyrocms/pyrocms#3597]
Hey guys, when are docs being released on migrations?
`artisan migrate` is not running any of my migrations 
`migrate:status` shows new migrations I've setup as 'N'
`artisan migrate:refresh` kills the database, and I'm not sure how to restore the installer db tables without a complete refresh through composer.
Any input you can provide on this?

**Comment by RyanThompson** [comment]
Hi Mike - I'm trying to get the Beta3 up and out by this next week and have the new docs module setup and populating but - in the interim - what are you trying to do? Install? If so run the GUI installer or the CLI installer like `php artisan install:streams`.

Otherwise, if you're already setup then you're completely migrated but not sure where you're at with a working installation.

Let me know a little more and we'll get it sorted ^_^

**Comment by uxinnuendo** [comment]
Hey Ryan,

Install is done.
I'm only looking to extend the database - is this wrong / not possible for pyrocms?

**Comment by RyanThompson** [comment]
You should be able to run migrations natively in Pyro, yes. I have not tried the generator for non-addon migrations though.. I will take a look this afternoon for ya.

PS - when I run migrate I get a bunch of nothing to be migrated messages but that’s vanilla install no custom migrations (but last time I checked this worked fine not that Im thinking about it).

**Comment by RyanThompson** [comment]
Should be good to go with B3 just out: `composer create-project pyrocms/pyrocms=3.0-beta3 --prefer-dist`
