### ISSUE TITLE
Inconsistency with content locale in CP when not english

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3628]
So, i have 3 locales: et ru en and et is defaulted in .env using LOCALE=et

When i start creating a new page, all is good. Estonian is the default locale. But when i try to save it, and i have not entered anything for english, i get error: The "Title (en)" field is required.

At the same time, title for Russian (ru) locale is not required. So it is inconsistent at best. Also it would make sense, that the default locale would be the fallback.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/f6eb5eb13b60016669b7c84a7188b398f92ff053

Was using the fallback instead of the default locale.

Only the default locale for your site is required. Since it's used by default if the others don't exist. Too much weight on the user / content team to have a value for all locales mandatory at once.
