### ISSUE TITLE
Module's composer dependancies and Illuminate conflic

### ISSUE THREAD

**Issue by websemantics** [pyrocms/pyrocms#3641]
Not a Pyro issue, but closely related, .. and more of, to see if anyone is having same problem and managed to solve it,

If I require packages local to a module and `Illuminate` package was a dependancy, I always get this issue:

```
PHP Fatal error:  Class Illuminate\Cache\FileStore contains 2 abstract methods and must therefore 
be declared abstract or implement the remaining methods (Illuminate\Contracts\Cache\Store::many, 
Illuminate\Contracts\Cache\Store::putMany) in 
/Applications/XAMPP/xamppfiles/htdocs/pyro/vendor/laravel/framework/src/Illuminate/Cache/
FileStore.php on line 250
```

```
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class Illuminate\Cache\FileStore contains 2 abstract methods and must therefore
   be declared abstract or implement the remaining methods (Illuminate\Contracts\
  Cache\Store::many, Illuminate\Contracts\Cache\Store::putMany)
```

Seems to be a conflict with Laravel itself, ..

**Comment by RyanThompson** [comment]
I would never require like this inside a module. Include this in your base composer.json if at all possible. A lot of the illuminate stuff has specific boot / registration procedure to set itself up that you would need to disable / copy / remove / fuck with :-/

**Comment by websemantics** [comment]
I learnt that the hard way, never allow illuminate packages in a Module's vendor folder. 

My fantasy was that, the system would support **autonomous modules** where the user could drop a module in the app addons folder, run composer, bower, npm, grunt etc locally and .. boom, it's fully functional, no install steps bore etc .. maybe with composer 2 hh

**Comment by RyanThompson** [comment]
You’re close - I think you can actually drop add ons in those folders and the require portion of the composer.lock file WILL get picked up but the dependencies will go to the root/vendor not the add-on vendor.

**Comment by websemantics** [comment]
What!! .. I mean, that's news for me .. quite good news actually :+1:  .. when you say composer.lock, it still mean running composer locally per addon? will experiment with this ..

**Comment by RyanThompson** [comment]
I meant composer.json lol

**Comment by websemantics** [comment]
Doesn't seem to work. 

Tried several scenarios, for example if the module is not installed, and when installed on both accounts composer doesn't pickup the required packages. 

It get hairy when the module is installed but required packages are not there yet because of the project composer.json file has pre/post scripts that has artisan commands, which breaks for missing libraries.

**Comment by RyanThompson** [comment]
I will have to take a look at it

**Comment by RyanThompson** [comment]
I can confirm this works when the add-on is required in the base composer.json file

**Comment by khoatran** [comment]
I had the same issue with another Laravel based CMS: OctoberCMS.  I would agree with websemantics's comment. We should not allow the vendor appears inside the plugin folder. 
The way I fixed this issue is just simply following below steps:

1/ Go through all plugin folders, remove the vendor folder
2/ Run the composer in the root of project. Certainly, the composer.json must include composer.json of plugin folder. You can check out the composer.json of OctoberCMS as an example in their Github repos. 

Boom -> everything becomes normal.
I comment my solution here with a lot of detail related to OctoberCMS because I have found the solution based on your ideas around here. I tried and luckily it succeed with me.

Somehow, this way puts the limitation of plugin installation. The way of installation with just the plugin (plus their vendor dependencies) is easier for the user to install. However, there is a risk of conflict when all of related libraries are loaded. So, we need to be very careful when trying to install plugin via the web interface (if it does not check dependencies and conflicts globally).

IMHO, I prefer installing the plugin and all of its dependencies via using composer in the terminal and work through to see whether any risks or conflicts happen. Plugin should not be something that non-tech guy should touch

**Comment by RyanThompson** [comment]
I will be indeed removing vendor folders in addons in favor of a plugin that merges composer.json files. That is in the upcoming release just as an FYI ^_^
