### ISSUE TITLE
Pagination should remember which page you were on after saving an entry

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3690]
To reproduce, edit an entry in any paginated list, on any page except the first page. Save the entry and you'll be taken back to the first page in the list. It would be hugely convenient if it were able to remember which page you were on last.

**Comment by RyanThompson** [comment]
SO! I would say - during the build process of every table all the time - it should run a "SetLastPage" command that sets the last page in session like "table-intended-page" = the page number with NO UNIQUE HASH (opposite of what I said on the phone).

The reason no hash is because as different tables are accessed the page should be reset - this way when you go back to ANY table after being somewhere it can check if the last page is set and redirect ON TO ITSELF on the correct page..

The tricky part would be avoiding redirecting the page to last intended when leaving a module to a non-table (which won't reset the value) then back to the table.

Then a `$builder->getLastPage()` would fire a "GetLastPage" command that extracts that value or null. 

Then you could do like `$redirect = $path . ($page = $builder->getLastPage()) ? '?page='.$page : null)` 

Might still need a hash, maybe this idea is trash, if it were a bet.. I wouldn't put down cash.. fuckin tired, about to crash. Night!

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/e8269b86ec7e526080819dfa7eeacb27e9a970bb

**Comment by RyanThompson** [comment]
Should apply to filters and page alike

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/8a35546bc63296b4097cb58d68c4937790411681
