### ISSUE TITLE
Twig "length" filter inappropriately returns 1

### ISSUE THREAD

**Issue by royallthefourth** [pyrocms/pyrocms#3726]
Using the Twig `length` filter returns 1 on my page fields, but not the template fields.

```
{{ template.meta_title|length }}
```
The title "Welcome" returns `7` as expected.  

With other fields, like my page.content field, I always get a result of `1`, no matter what's actually in the field. This particular fields is a WYSIWYG.
```
{{ page.content|length }}
```

**Comment by RyanThompson** [comment]
This is because the Entry and it's fields are wrapped in Presenters. To test the length of the value of that field you need to use `{{ page.content.value }}`. What you have would display find (it fires `__toString`) btw with the `|raw` filter what you have there is this: https://github.com/anomalylabs/wysiwyg-field_type/blob/master/src/WysiwygFieldTypePresenter.php

Which is why you can do `{{ page.content.reder|raw }}`

**Comment by bloveless** [comment]
Will you try {{ page.content.value|length }}

**Comment by bloveless** [comment]
Dang it Ryan! You beat me to it!

**Comment by RyanThompson** [comment]
Really hate to rub it in but my answer was better too ;-)

**Comment by bloveless** [comment]
Ouch!
