### ISSUE TITLE
Broken images and icon on Dashboard

### ISSUE THREAD

**Issue by liuflowt** [pyrocms/pyrocms#3751]
![icon path](https://cloud.githubusercontent.com/assets/20101964/16290989/a441e642-3934-11e6-9ef0-a838b47e373c.png)

**Comment by RyanThompson** [comment]
From my own practices here - I am not sure if this is Pyro or not. If I load the SAME site in non-path (vhost) they all load and upon returning to the path version they all display since they got published. Like it could not write the file or something.. Thoughts?

I have localhost pointing to my sites/ root and workbench.local pointing to sites/workbench.local/public for example.

**Comment by RyanThompson** [comment]
Nope - confirmed it's an issue - already have a fix will be pushing soon.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/361f69829685ed015e09d55cc40f554b565e5b2c

**Comment by liuflowt** [comment]
It's working. Thanks!

**Comment by RyanThompson** [comment]
Thanks for the help!
