### ISSUE TITLE
General optimization considerations

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#3847]

**Comment by onyxg** [comment]
Found Illuminate\Support\Arr method exists($array, $key) is consuming 0.5-0.4 seconds
appears this is due to the old issue of isset vs array_key_exists. 

debugging to follow.

References:
http://stackoverflow.com/questions/6337893/why-is-array-key-exists-1000x-slower-than-isset-on-referenced-arrays
http://juliusbeckmann.de/blog/php-benchmark-isset-or-array_key_exists.html

**Comment by onyxg** [comment]
**Disable xdebug.**

Comment out the following in your php.ini file:

FROM
zend_extension=php_xdebug-2.4.0-7.0-vc14.dll

TO:
;zend_extension=php_xdebug-2.4.0-7.0-vc14.dll

**Comment by onyxg** [comment]
**Enable PHP Module OPcache.**

Enabling OPcache gives you major gains when running PyroCMS, make sure you have this enabled. See manual for installation instructions:
http://php.net/manual/en/opcache.setup.php

**Comment by keevitaja** [comment]
php's native `in_array` has the same n+1 problem/logic as array_key_exists

**Comment by onyxg** [comment]
Consideration of the following changes to retrieving installed modules & extensions.
these 4 queries are run for every page, any database call is expensive and should carefully be considered as if truly necessary. 
``` 
select * from `default_addons_modules` where `installed` = '1' and `enabled` = '1'
select * from `default_addons_extensions` where `enabled` = '1'
select * from `default_addons_modules` where `installed` = '1'
select * from `default_addons_extensions` where `installed` = '1'
```

I would like to advise the following speed changes

**Option 1** 
Do only 2 selects full table selects, due to the limited number of rows in these tables, doing a full table select has minimum overhead (whose going to have 100+ modules/extensions installed).
Once retrieved from the database we store these results in the model/variable/instance then using code to retrieve by keys - installed/enabled, this reduces the number of queries by a factor of 50%.
> Also these tables modules/extension have exactly the same columns, a further improvement would be to create a single table, adding a type column EXT/MOD and doing only "1" full table select, removing all but 3 queries.
```
select * from `default_addons_modules_extensions`
```

**Option 2**
Completely remove these 4 queries by means of caching results.
As i unaware of the value/full details of checking what is/isn't installed/enabled upon each load of PyroCMS, i would imagine the only time we really this to refresh/reflect this is **1.** when you login to the backend and what to disable/enable a module/extension. **2.** when a new module is installed ie: via composer (unsure if modules are automatically installed)
Because of the above 2 items, i would imagine we can therefore store/cache the result of these 2 queries, removing the database overhead and rather use cache file / or whatever the specified caching method is set to.

Speed gain for this change - going option 2, can be around 2-5ms per request.

**Comment by onyxg** [comment]
Pluck - with no select column appears to have a minor speed issue, unsure as to the actual reason, factors include mysqld collecting unused column data, Laravel preparing unused data or Laravel's pluck method looping through unused columns, this method does however appear somewhat costly.
Upon testing the following code, a tiny speed improvement is seen.
**Change:** Whenever Pluck is used to get that column, the query should include a select also ONLY for that column.
In all times of testing this code Pluck 2 (with select) comes out as the winner.

```
      $e = microtime(1);
        $r = $this->where('installed', true)->get()->pluck('namespace');
      $s = microtime(1);
      var_dump($r);
      var_dump('pluck 1: '.($s-$e));

      $e = microtime(1);
        $r =  $this->select('namespace')->where('installed', true)->get()->pluck('namespace');
      $s = microtime(1);
      var_dump($r);
      var_dump('pluck 2: '.($s-$e));
```
example difference:
pluck 1: 0.0013270378112793
pluck 2: 0.0011138916015625
>> 0.2 milliseconds.
compounded by for example 30 queries = 6 millisecond speed improvement overall

**Comment by onyxg** [comment]
The module - Anomaly\UsersModule method onRegistered takes an little long to run compared to other modules, between 15-50 milliseconds (currently my homepage speed load is ~600-800ms, so this is a minor chuck of that, for just for one module.)

Upon timing the dispatch method appears to consume majority of the time. Initializing the method new SetGuestRole is negligible.

`$this->dispatch(new SetGuestRole());`
