### ISSUE TITLE
Unable to purchase a module in pyrocms

### ISSUE THREAD

**Issue by aqilkam** [pyrocms/pyrocms#3906]
Hi,

I am trying to purchase a module from pyrocms 

https://codeigniter.pyrocms.com/store/details/forums

i did the registration, its not taking me anywhere and i am unable to purchase this module can you please help me out with the purchase of this module.

Thanks
Aqil

**Comment by ikoniqoz** [comment]
Hi aqilkam - Unfortunately, this module is no longer supported by the creator and it would require some effort to get it up to date and fully functional with PyroCMS 2.2.5(Dev). 
Also, I believe that the old Store is no longer in full operation since all current effort is focused on the V3 branch.
Hope this helps.

**Comment by RyanThompson** [comment]
@ikoniqoz the old store is most definitely operational. But requires a little manual touch since archiving everything. Users for one are not automatically registered.

The forum module.. Idk how it even performs but there is a brand new Forum module for v3 that you can see in action (out of the box) here: http://pyrocms.com/forum

**Comment by RyanThompson** [comment]
@aqilkam what is your username I can activate you.

**Comment by ikoniqoz** [comment]
@RyanThompson - thanks for the tip on the Forum module for v3. - It works great on pyrocms.com - It it released for purchase somewhere ?

**Comment by RyanThompson** [comment]
It's only available under the presale special right now.

**Comment by ikoniqoz** [comment]
OK - Thanks. Looks like I will have to wait til those bits are made generally available.

**Comment by aqilkam** [comment]
the registered details is

Email: aqil207@gmail.com
Username : aqil
