### ISSUE TITLE
[streams-platform] ModelObserver events not fired

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3946]
Hello!

I am not 100% sure, when events updating and restored should be fired, but in my module and pages module, the TypeObserver does not fire 'updating' when type is updated. Same thing with restored.

**Comment by RyanThompson** [comment]
What you are seeing is the TypeObserver not updating because the model is not dirty. If you update the name / description that's the Type's translation model which according to Laravel is separate. Might be beneficial to fire observer methods from translation to base model but.. there would need to be a good argument.
