### ISSUE TITLE
Pages module and Multi-language ideas/problems

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#3982]
Ok, so we have PAGES module, which works really well, BUT! Not in all circumstances.

For example I create a page;
“About us” - with slug - “/about-us” which is OK.

But what about other languages, let’s take Lithunian:
it would be:
“Apie mus” - and slug should be ‘/apie-mus’, maybe even: “/lt/apie-mus”

Why I am adding ‘prefix’ /lt here, is so that SYSTEM does not ‘loose’ the current language.
So it could be in German ‘/de/uber-uns” etc. And if someone shares this URL, I go to site, and see all page in German.

Now current language detector can work on subdomain: ‘lt.domain.com’ and using 
“?_locale=lt” GET parameter, which is very bad for SEO, google – will crawl only some languages etc and that will end in unpredictable results – at the end you are not sure which page was indexed...

Because now I can’t simply copy URL and send it to you, and If I want you to show the ‘lt’ version of the site, I’d need to append “site.com/about-us?_locale=lt” or something like that, but anyway this does not seem correct to me :(

One of the solutions maybe would be:
when you create a page, you create it as normal, but with untranslatable etc… 
Later  create ‘dummy page’ just with a slug ‘/lt’, and when a page is a child of this ‘tree’, you have 1-st segment of URI as a language detector. If it is not detected – then default locale is used on the site.

It’s somehow hard to express all the concerts etc, but as I see now, only Pages module now is missing some stuff.

Maybe we would just need to
1 - copy core pages module and modify it to our needs
2 - improve the language detector – and it will make everyone happy?

How others feel about this pages/languages stuff ?

**Comment by RyanThompson** [comment]
My personal opinion on this is to delegate this to the page handlers. This kind of control will be introduced in Pages v2.2 where handlers will play a larger role.

What would happen is the path would stay the same because it NEEDS to but your handler can allow setting a slug per language (call it segment maybe) and will route based on that. 

This way we can keep things clean, allow for extension (and many other ideas but this one will then be possible) and make everyone happy ^_^
