### ISSUE TITLE
[Feature request] create specific artisan commands for extension, add-on, plugin and module

### ISSUE THREAD

**Issue by rabol** [pyrocms/pyrocms#4053]
Due the fact that extension, add-on, plugins and modules are different there should also be different commands to scaffold 

I do know that that make:addon will do the trick, but it is not logical to use make:addon when you create e.g. a extension.

each the command should also work slightly different

it should auto add the -extension, -module
e.g

php artisan make:extension vendor.test

should create /addons/<appref>/vendor/test-extension

php artisan make:module vendor.test
should create /addons/<appref>/vendor/test-module

the make:module should also by default create a fields and a stream migration

the created composer.jason should contain the same entries as seen in the admin panel - by default there is no dummy entries for author and support

**Comment by RyanThompson** [comment]
I can see where different addon flavor commands might be nice if there were options. 

module:install used to be that way but then I added addon:install since they are nearly identical. I just have some logic internally to handle different chores. Same with the make command. I could see more of a make:addon fires off the other command if anything.

Can you tell me, what’s the driving principle behind this that would be fixed by separating them? If there are no options it seems making an addon - by dot notated namespace, is pretty logical since it’s the same procedure everywhere. 

I will say though I don’t like the idea of only using part of the namespace for the command. That’s not done anywhere else in the system and that’s usually a good sign that it should be avoided (at these operating levels anyways).

Thanks for the input! I need to hear more.

**Comment by rabol** [comment]
Since there is the add-on, extension, plugin and module concept, there must be some differences and therefor there must be different needs or elements that needs to be developed for each type.

At the moment there is special artisan commands for addon e.g. php artisan addon::install and extension e.g. php artisan extension:install so therefor it would make sense to have a make command for each maybe extension:make instead of make:extension

The various ways to add functionality to PyroCMS is a little blurry, and it just adds to the confusion that one have to use: php artisan make:addon to create a module or an extension

I do not think that I suggest that the namespace is part of the command or that is not my intention on the other hand today the type is postfixed to the name which is a 'funny' way to distinguish the different types

A more clear separation would be to have each type in a separate folder structure, but i totally understand that changing the current structure will be more complicated.

having separate commands would also allow different features or restrictions for each type e.g an extension should be extending something that is already in the system like a stream, and add-on should be an add-on to a module

**Comment by RyanThompson** [comment]
I totally get where you're coming from here. And to touch before I continue on the folder structure - it's designed to follow composer directory structure so they are all in the same dir. 

On the commands.. I think I will end up splitting them off. But, I won't be doing it until the commands perhaps grow a bit more or if they grow (more features / options / etc).

In the install case the addon:install actually came afterward cause I was tired of the two commands since they do the same thing. Idk kinda depends I suppose.

Im going to close this down for now but it's definitely on my mind for when things start moving around in that area of the application. We'll have to see ^_^

Thanks for the input!
