### ISSUE TITLE
Initiative to organize fields as a principle!

### ISSUE THREAD

**Issue by RyanThompson** [pyrocms/pyrocms#4190]
@mattcdavis1 and @designbywilliam and others interested:

https://github.com/pyrocms/pyrocms/issues/4179#issuecomment-283562660

I feel like the entire CP can benefit from better organization leveraging tabs. But, here is my fear: I don’t like the idea of common options / values being stuffed behind tabs where it adds mental tax to look for / adjust them. Some of this is better default values - some is organization choices.

Would you guys start an initiative on here to go over the CP in general and let’s come up with some solid principles on how forms should be organized by default including BOTH tabs (horizontal / stacked as needed) and sections ALIKE. 

If we can focus on principles and rules then we can simply apply them systematically.

**Comment by mattcdavis1** [comment]
I'm still thinking through this and looking through the different modules to work out implications but some initial thoughts:

* Non-required fields (or required fields that can be set to a sensible default) that can be logically related to other fields should be grouped together and placed in secondary tabs.
* Repeating fields should generally have their own tab (possibly with other related fields - i.e. Image Gallery Heading, Image Gallery Repeater)
* In some cases putting required fields in non-default tabs may be worthwhile, but the default practice should be to try and avoid this.
* User configurable modules such as pages and streams should provide a means for users to assign fields / field sets into tabs (ideally via GUI but at minimum via config) themselves rather than being forced into any pre-set structure.

Some additional tab related thoughts

* It would be nice if every module was easily override-able as it pertains to the decision of whether or not to use tabs and which fields should be assigned to which tabs
* It would be nice to have multiple tab-style options (vertical / horizontal)

Some additional considerations - not related directly to tabs but to the form UI generally:

* I think overall there is generally too much vertical space and the fonts are too large.  This makes it less likely that users will be able to see a group of items together in one screen.  Personally, i feel a bit disoriented looking at some of the larger forms.   I think something like [this](https://goo.gl/QTYH2m) would be an improvement.
* I think it would be helpful to consider multi-column rows.  For example, does [this](https://goo.gl/SGpZK3) really need 4 rows (as opposed to one row with 4 columns or 2 rows with 2 columns)?

**Comment by RyanThompson** [comment]
FanTASTIC first thoughts @mattcdavis1 thanks a ton. Here's my thoughts on a few of these items;

> Non-required fields (or required fields that can be set to a sensible default) that can be logically related to other fields should be grouped together and placed in secondary tabs.

My thoughts exactly on this. If it's not required / sensibly left to default values then it can be tucked away in a relevant tab. Page options is a great example. 

> Repeating fields should generally have their own tab (possibly with other related fields - i.e. Image Gallery Heading, Image Gallery Repeater)

Agreed and on that note - related fields in general. SEO for example I think makes sense in an SEO tab. This would make it easy to add fields to this tab from the outside being able to assume there is an SEO tab to add fields to using builder functions that let you target positioning of sections / tabs for insert.

> In some cases putting required fields in non-default tabs may be worthwhile, but the default practice should be to try and avoid this.

This makes sense for common toggle options maybe? Not required / sensibly defaulted but often accessed perhaps. I can agree with that.

> User configurable modules such as pages and streams should provide a means for users to assign fields / field sets into tabs (ideally via GUI but at minimum via config) themselves rather than being forced into any pre-set structure.

My thoughts are that perhaps the module's out of the box structure can be set with config.. But it'd be nice to be able to be able to do this globally without "adding the logic to allow it" to every form (and table for that matter).

Put your brain to work on trying to figure out a global pattern we could use aside from I guess the obvious binding of builders.. which works fine but is a little clunky.

For CUSTOM / user defined fields I feel like there should be a designated zone where you can add sections / tabs etc via GUI. That's 100% on my radar. 

> It would be nice to have multiple tab-style options (vertical / horizontal)

We do have this - I snuck it in a bit ago. Will doc when we implement it.

> I think overall there is generally too much vertical space and the fonts are too large. This makes it less likely that users will be able to see a group of items together in one screen. Personally, i feel a bit disoriented looking at some of the larger forms. I think something like this would be an improvement.

Idk about the fonts size.. I am trying to think of big dumb users and devs both. But the horizontal strain is the idea behind this process. We'll drive that down considerably.

> I think it would be helpful to consider multi-column rows. For example, does this really need 4 rows (as opposed to one row with 4 columns or 2 rows with 2 columns)?

I feel like it would behove us to address columns in a phase 2 if necessary. Im not particularly interested in column choices just yet.

Well this is fantastic - let's continue to beat it up a bit. Turn up the burners on these and continue to reduce it down to some very super solid principles ^_^

Thanks!

**Comment by ikoniqoz** [comment]
Hey - This is great stuff. Many thanks to @mattcdavis1 for putting this out to us. Looking forward to the process as it evolves.

**Comment by RyanThompson** [comment]
@mattcdavis1 any more to add on this front before I really dig in? I figure I'll have a go at applying these to a few forms and see what happens.

**Comment by mattcdavis1** [comment]
@RyanThompson - not at the moment.  next thing was just to work through the implications on a module level.  Probably better done on your end.

**Comment by stefanpkc** [comment]
About font size like @mattcdavis1 mentioned. Sometimes it's too large and sometimes you want the field type to be more compact. When you have 3 field types that belong together, you maybe don't want to display a label on top but in front of the input. So a compact mode or a way to render the field type differently could give more flexibility.

**Comment by RyanThompson** [comment]
@mattcdavis1 agreed I'm on it! @stefanpkc I agree a compact mode would be nice.. on a global level. Ill think about it. Thanks!

**Comment by stefanpkc** [comment]
@RyanThompson, if you do a compact mode.. there will always be scenarios where other people need 'a different' mode. So perhaps it should actually be a mode or style setting and a Twig file you can easily override. If no override Twig file is found, it will use the default.

**Comment by RyanThompson** [comment]
Ya I just want to focus on the 99% :-P

**Comment by RyanThompson** [comment]
Well done all and thanks again @mattcdavis1 ! I've got it from here on out and replace PRO addon forms with tabbed as I come about them ^_^
