### ISSUE TITLE
Feature Request [streams-module] Allow changing of field type

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4219]
Currently there is no way to change a field type which is frustrating.  Please provide a dropdown for selecting a field type.  Ideally, we could just kill the field type modal altogether and use this dropdown in conjunction with an ajax call for form fields on both create and update (isn't that the way it was with pyro V2?)

**Comment by RyanThompson** [comment]
I want to keep the modal / simplicity of the system.. BUT I think maybe a dropdown will be nice? Otherwise a "Change" button (next to cancel) or we can put the change button on the table and have it open the "edit" form with new field type configurations. 

I like to avoid Ajax where it doesn't make sense. In this case all it would do it add unnecessary complexity.

So the logic is in there now - this is ready for UI basically. I think:

1.) Change button on table behaves like edit button but for new type (using modal to select)
2.) Change button in form does basically the same thing (adds a click though cause you have to edit then change..)
3.) A drop down in the form that reloads the page on change with new configuration options.

Thoughts? @ designbywilliam what do you think?

I am leaning towards #1. 

Also worth noting all the assignment logic and stuff is gonna be pushed off to a core controller with this new feature too. The controller will be configurable and will make it easier to implement, more consistent, reduce overhead of addons, etc. So this will be the baked in way things work.

**Comment by RyanThompson** [comment]
Kinda long winded but basically this is ready but for UI :-P

**Comment by mattcdavis1** [comment]
From a user experience perspective  i think the ajax option is better because you maintain your exact position on the page and the time to a new usable form is shorter.  In my opinion user experience should be the top priority and technology / implementation concerns should be secondary.  I think the modal should be done away with altogether and replaced with a dropdown/ajax on the field create / modify page.

However, my bigger concern is just that the functionality is there.  To that extent, i would be glad to see any of the options mentioned implemented.  Of the above options i think #2 is the better option.  Changing a field type is a way of editing it so logically this is a subordinate operation to "Edit" and should be handled there.  Alternatively, the button could be in both places but i think just the form is probably the best option.

**Comment by RyanThompson** [comment]
@mattcdavis1 I understand the Ajax from user perspective but simplicity is a principle for Pyro - it's just not as clean to implement given the standalone nature of FTs. I don't think it's so much a positive to most users to justify the work / complication to implement it right now.. Hopefully that makes sense :-/ If it were a grand improvement I would by all means implement it but I don't believe that to be the case. I think it'd just be "nifty" and I know our clients (we've got a good crowd to poll) wouldn't care either way. Which is a red flag. In my experience with Pyro the most reduced / common denominator and consistent approach has proven to be the best.

However - I think I agree with you in #2 because I would like to add some confirm logic to this perhaps.. It could potentially destroy data (text input to integer for example).

Let's see what william thinks ^_^

**Comment by designbywilliam** [comment]
Obviously i agree on the user experience discussion when it comes to ajax. With both of you:) But my personal preference is to keep it as native as possible because it's true to the core and i believe in such systems.

I think #2 is my preference. Because of the potential problems it could cause, it's one of the situations i think an extra click is definitely worth it.

_(Not part of this discussion, but when it comes to the talk having more ajax/js in the admin. From my personal perspective, i would rather see Ryan focus on adding more core/PRO modules (stuff) than thinking about it. Because that is how PyroCMS v3 will become better and better and start bringing in money to Ryan as well as allowing us in the community to contribute with our own addons and sell in the shop. On that note,  I think it's better if another community member focused on a javascript version of the admin theme and sold it.)_

**Comment by RyanThompson** [comment]
I brought in a core utility to implement changing fields and including it in your own custom field/assignment stuff as well as core addons. But I have to implement it as it's a slight change from the manual way I've been doing it.

**Comment by RyanThompson** [comment]
Will update the addons accordingly as I can! Unless someone wants to make the swaps - it's very easy.
