### ISSUE TITLE
[accelerant-theme][feature] Suggestions for improved flexibility in Control Panel Navigation

### ISSUE THREAD

**Issue by haeflimi** [pyrocms/pyrocms#4239]
I think the Navigation Module that comes with the core is a great tool for decoupling the navigation structure from actual functionality/ content structure. I have used it building Frontend Navigations back in the days with PyroCMS 2 and loved it for it's flexibility and ease of use.

But why isn't it utilised for building the Control Panel Navigation? - It would make so much sense and the Control Panel so much more flexible and easier to customize.
If we could just open the Navigation Module and change around/ remove and add things in the Control Panel Navigation- That would allow us to easily tailor the Navigation structure in the backend to the needs of our admin users/ content editors/ image uploaders/ etc.
This could be driven a step further by allowing us to assign different Navigation Menus to different User roles.
Right know i can't even use the Module to create a separate/ alternative Admin navigation and implement it in my frontend because it doesn't allow me to choose Admin/ control Panel Pages as Link Targets.

Of course there might need to be some Limitations that need to be figured out and implemented. Certain things probably shoudn't be completly removable from the navigation for example.

**I think this kind of flexibility could be useful in different use cases:**

- Suppose i wanted to completely rearrange the Navigational structure in the Control Panel (maybe in order to mirror some kind of business logic/process).

- Suppose a third Party addon developer decides to not implement Permissions in his Module. - So it shows up for every User in the control panel. But i dont really want my "only-article-posting-content-slaves" Users group to acces or even see it.

- This issue might could be sattisfied as well: https://github.com/pyrocms/pyrocms/issues/4224

Maybe i am missing something but as far as i see it, the only (or maybe just most obvious) way to satisfy these use cases right now would be to create a custom admin theme and replace the bits that generate the side- and topbar with some custom code. (that would problbly end up beeing quite static.) 
That way i would miss out on any future improvements on the accelerant-theme witch i dont think is a great solution at all.

Any thoughts on this?
Or any hints on ways that i have missed to modify the Control Panel Navigation?

**Comment by RyanThompson** [comment]
Hey Michael!

This is really a good idea - but it strikes me as something you'd have to opt yourself (and can easily do so). For example run `php artisan addon:publish accelerant` and modify the sidebar / views required.

However there are a good number of things that would make this very painful:

1.) Permissions are role based AND user based. Making a nav for each role would be rough enough let alone a nav for each user specifically.

2.) Does not support icons which is a necessary component for the admin theme.

3.) The main navigation and especially module sections (the inner sidebar) are very often tied to logic and rely on triggering modals and conditional display. They use a builder system which can be / will be able to be hooked into for notification bubbles and such so that would be difficult handling it with the navigation module.

4.) Automation is king! As long as it can be customized. And currently you can already customize the navigation order in both Settings and Preferences (user specific) under the Themes section -> Accelerant theme.

There are a few other aspects regarding functional integration / search is coming / and a few miscellaneous items that would be more difficult to integrate with the nav module. BUT.. again you can do this if you want. Feel free to fork the admin theme too if you do it often!

Besides these points though you'll be happy to hear more integration features are coming for the control panel.

Hope this makes sense! Sorry though there's too much momentum and features coming here to consider changing :-/

Cheers!

**Comment by RyanThompson** [comment]
We've since added the ability to integrate with navigation and also reorder it manually down to per user overrides if desired (from settings/themes -> accelerant theme)
