### ISSUE TITLE
[Files Module] Store Thumbs in Same Location as Image

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4249]
If a file is stored on S3 (or any other provider), the image should be stored there also.  Even though thumbs are smaller in size the space still adds up when you have tens of thousands of images.  On our hosting we typically store 7 days backups and then full server backups.  So each file on our server is multiplied by 7 and there is an increased cost for backup storage as well as potentially needed a large server sooner than we otherwise would. It is possible to exclude certain directories from backups to help mitigate this but it is a pain to manage (and still doesn't do anything to deal with the size created from the original thumbs).  

I'm not sure what the rationale for storing thumbs in a separate location from the primary image is, but i don't think this is ideal. In addition to the above mentioned issue, storing thumbs locally also causes more issues cross-environment.  If the thumbs are stored in the cloud, they will show up locally as well.

**Comment by RyanThompson** [comment]
Storing thumbs / communication back and forth from CDNs / other tenants is extremely costly vs a local filesystem. Because thumbs are volatile (you can trash them anytime / it's basiclaly cache) it really makes sense to store them _as_ cache locally or maybe even in a memstore or something fast. 

Make sure to use $file->url() or {{ file.url() }} in code though to make sure you're referencing your edge/CDN and not requiring Pyro to make any alterations. Otherwise the generated image would end up on your filesystem too. 

I could definitely see this as being optional (toggle off live thumb previews) but I think it's a bad idea to use a CDN as a filesystem cache for image previews.

One of my plans moving forward is to figure out a good way to cache generated images on the same disk though. I could see perhaps if you wanted you could tell pyro to do this for ALL generated images but I don't foresee that being the default. Again it's like storing your cache on the CDN. But I have a need very often to take the user input image from S3 and manipulate it for optimum web use and put it back on the server but currently that is not possible. Won't be hard to do though. 

In our previous situations like you mention - as well as something like a Heroku dynamo we just ignored public assets / image caching all together cause it's generative. Same as you could ignore your cache directory / session directory / etc.

**Comment by mattcdavis1** [comment]
When you say storing thumbs on remote storage (S3 wouldn't be a CDN) is "extremely costly" vs. a local file system - what do you mean by this?  Are you talking about disk operations such as file_exists?  Couldn't this information be stored in the database file entry (i.e. has_thumb)?

> One of my plans moving forward is to figure out a good way to cache generated images on the same disk though

This was exactly what I requesting (i.e. if my disk were S3, the thumb would be stored there).  Were you thinking that i was asking something different?

Just to clarify then, it sounds like you are were already working towards implementing my request - that generated images (which would include thumbs) would be stored on the same disk as the image.  Is that correct?
