### ISSUE TITLE
[Streams Core] Provide option to exclude addon loading when not necessary

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4281]
I just created 4 extensions for sole use with my backend admin theme.  There is no reason why the service providers for these extensions should be getting called when loading a front end page.  This is just inefficient.  

Ideally, addons could indicate whether front-end/backend loading is required, optional or unavailable for a given context (admin/ front-end - in the above instance, my module would indicate admin only and users wouldn't even have the opportunity to load it on the front end). Users could then choose if they want to load the addon or not in a given context (for addons that show either admin or front end as optional).  

The files module, for example, has both front and backend routes.  However, i may choose to not use the front-end functionality.  In this case i wouldn't want the overhead of the service provider getting loaded.  Or, i may want to only load the files module on certain pages in which case i could load the service provider manually just for the pages i want to use it on.

From a UI perspective this could probably be handled with a lightswitch in the addons/ and addons/extensions listing views (along side install/uninstall).  Or maybe no UI and just config only.

**Comment by fryiee** [comment]
Doesn't this go against the whole concept of Laravel service providers? And if we're talking about utilising deferred service providers, that only works on service providers which just provide bindings - I'm sure most the service providers for the various modules don't do that. Unless I'm misunderstanding?

**Comment by mattcdavis1** [comment]
@fryiee - i don't see how not loading something that's not needed violates any principle except that of inefficiency.  Currently, the main performance bottleneck in Pyro is the addon loop - that's why this concerns me.  As far as deferred providers, i'm not really sure how that works but ideally something that is not needed for a given request should not generate any overhead at all.

**Comment by RyanThompson** [comment]
I've thought about this before. It might be able to be done to some extent easily with `provides` options for the providers. But in general this is tricky and pretty complicated. Because then we introducing an addon loading layer where basically nothing is loaded until the loader says so.. which I am not against. But seems very CodeIgniter-ish. I understand the inefficiency and indeed it would speed things up.

For example though I believe we would still need to detect addons and we might also need to autoload all the same.

Another example would be what is the relationship ft is pointing to a relation in an "unused" addon. Then the FT has to detect the location of that addon and make sure it's loaded.

**Comment by RyanThompson** [comment]
I think a toggle is less intuitive than a loader / dependency guard in this case btw - but that's just my opinion.

**Comment by mattcdavis1** [comment]
@RyanThompson - agree that it is a complicated issue but it think it is an important one to address one way or another.  I'm currently working on an admin theme and trying to push out a fairly involved pyro build at the moment but i do intend to take some time to look into options for improving performance on my end as well.

As far as the method of managing addon loading logic (toggle vs something else), personally i don't really have a strong view one way or another.  Just want some means to accomplish the end.

**Comment by fryiee** [comment]
Do addon service providers *only* register bindings @RyanThompson ? Otherwise you won't be able to use `provides`. I think we would need to develop a custom loader to get the currently used addons with the ability to bootstrap service providers if something hits a class / stream namespace that needs it - definitely non-trivial. And obviously any service provider that adds a `boot()` function will have to be autoloaded regardless.

**Comment by RyanThompson** [comment]
I have some ideas and this is super on my radar - Ima close this for now since it's being handled. Cleaning up :-P
