### ISSUE TITLE
Class 'Faker\Factory' not found

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#4289]
Hello,

after some update, I am not able to run backend/frontend without Faker installed

**Comment by fryiee** [comment]
Check your composer.json for "fzaninotto/faker": "~1.4".
it was added as a dev dependency but depending on the age of your install it may not be present. This happens after you create a stream since test scaffolding was introduced into core (as it scaffolds a default factory for your stream model). Just add that line to your composer.json and composer update.

**Comment by fryiee** [comment]
This is because `AddonServiceProvider` always registers factories on register which instantiates `Faker` even though faker is only in `suggests` in the https://github.com/illuminate/database package. Either need to conditionally load it or move faker into regular dependency.

**Comment by RyanThompson** [comment]
Need this: https://github.com/pyrocms/pyrocms/blob/3.3/composer.json#L82

**Comment by huglester** [comment]
Let's make it the corrent way then:
https://github.com/pyrocms/pyrocms/pull/4291
