### ISSUE TITLE
[repeater-field_type] Issue On Frontend 

### ISSUE THREAD

**Issue by davestar057** [pyrocms/pyrocms#4309]
On the FRONT END of a website, when using [repeater-field_type] in a form loop it displays the repeater fine, and you can add/remove etc - However when it comes to submitting and saving the form data, everything saves fine, however it does not save the repeaters data or the relationship etc... it doesn't save anything.

Code in loop to display is just along the lines of

```
{% if field.field == 'addon_customers' %}
<div class="form-group">
{{ field|raw }}
</div>
{% endif %}
```

It does however work fully and saves everything as it should when using with $form->render(). @RyanThompson

**Comment by mattcdavis1** [comment]
I'm running into this issue also. For me, i didn't even get to the saving part because i was still trying to get the validation working.  When i submit a form with a repeater from the FE and the page reloads with errors, the data in the repeater fields is not re-populating. Think i've spent about 2 days trying to get this resolved.  

Sounds like even when i get the validation resolved i'm going to run right into another issue with saving.

**Comment by mattcdavis1** [comment]
It looks like the issue with validation at least is a combination of a couple of things:
1. The FormController fails to send back repeater field data in the flash response
2. Even when i add request()-flash() to the builder response there is still an issue in: `Anomaly\Streams\Platform\Ui\Form\FormBuilder`.  For non-post requests the form builder runs the `PopulateFields` command rather than the `PostForm` command.  All the `PopulateFields` command does is:
```
foreach ($request->old() as $key => $value) {
    if ($field = $this->builder->getFormField($key)) {
        $field->setValue($value);
    }
}
```

Which of course will fail for repeater forms because their request keys are named like `states_counties_1_state`, `states_counties_2_state` etc.  

I temporarily pasted in a bunch of the commands from the `PostForm` into the `PopulateFields` command and my data started showing up again on reload with errors.  

@RyanThompson - this is a pretty significant issue (inability to use repeaters on front end forms).  Any chance we could prioritize this?  I'm working on a FE form for a client now and this issue has been a real problem for me.  I'm trying to hack together something now but would be great to have a fix here.

**Comment by mattcdavis1** [comment]
One other thing @RyanThompson - what is the rational for using $_POST directly in a number of places in core rather than the request object?  Initially when i was troubleshooting this i did a request()-merge() of old() data and wondered why it wasn't getting picked up.  Then i realized there are places where $_POST is being accessed directly. Unless there is a specific reason for this i think we should stick to request() for consistency and also so we can modify request without touching original $_POST data..

**Comment by mattcdavis1** [comment]
My current workaround for this issue is:

1. Add `request()->flash();` in `FormController@handle` method

2. Add middleware that runs on every request and executes the following:
```php
// temporary workaround for FE form issues
if (!($request->segment(1) == 'admin')) {
    if (old('action')) {
        $_POST = array_except(old(), ['action']);
    }
}

return $next($request);
```

3. Add below code to `PopulateFields@handle` after the $request->old() loop:
```php
if (!IS_ADMIN && $_POST) {
    if (!$this->builder instanceof MultipleFormBuilder) {
        $this->dispatch(new ValidateForm($this->builder));
    }
}
```

The only issue i am seeing with this workaround is that repeater errors don't show in the main errors array (but they are available in the form fields).  However, this also does not address the main problem of not saving.  Looking into a workaround for this now.

**Comment by mattcdavis1** [comment]
hmm - i'm not experiencing the issue with the repeater fields not saving.  Sounds like that issue is limited to only certain methods of FE form setup.  My setup is actually not using the render() method and still works fine (i'm adding each field individually so i can fully customize placement and html).  The only definite issue i'm seeing is related to Repeater validation and repopulation (at least with the way i'm using the FE forms).  

@davestar057 - are you seeing issues with repopulating / validation of repeater fields on your end using the render() method?

**Comment by mattcdavis1** [comment]
Just realized i can just manage the form the same way streams module does until the form handler controller issues are resolved.  Much easier and no hacks (although i think the form handler options is better once it's working since i don't need to setup my own controller for that)

**Comment by RyanThompson** [comment]
$_POST should be replaced with $request use especially in controllers where $this->request is available. Old code is likely the reason.

**Comment by RyanThompson** [comment]
Can you reduce the above discoveries into a simple actionable list for me? I should be able to fix this relatively easily from looking at it briefly.

**Comment by RyanThompson** [comment]
I believe this has been fixed!
