### ISSUE TITLE
[streams-platform] Slugify stop works if you change tab in form

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4312]
Think that Pyro should have own slugify plugin

**Comment by RyanThompson** [comment]
Ive never gotten that issue before. What's the console error you're seeing?

**Comment by bloveless** [comment]
I've had slugify stop working if the form remembered a different default tab other than the one that contained the slug. But since this memorization has been removed I can only assume that a simple update will solve this issue for @Piterden or making sure that the slug is displayed on the page when it is initially loaded.

**Comment by Piterden** [comment]
Maybe would be better to reinitialize slugify on tab changing too.

Else I have seen, that my PR with memorization works not correct if I have 2 rows of tabs. Like there:
![image](https://cloud.githubusercontent.com/assets/5930429/25096196/e73962f0-23a7-11e7-967f-046444b3e245.png)
See? Top row have all disabled. @mattcdavis1 had talked about that problem.

That should to be fixed.

**Comment by RyanThompson** [comment]
I’ll mess around with it and try and reproduce now that the sticky tabs are gone.

**Comment by RyanThompson** [comment]
This has been fixed
