### ISSUE TITLE
[Files Module] URL generation extremely slow

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4314]
In the code below (`property` is a streams entry and `property_documents` is a multiple files field type), if I exclude the `<a href="{{ document.url() }}">{{ document.url() }}</a>` my page loads in appx 500ms (there are 4 files in this loop).  Adding the line with the url generation increases the page load time to appx. 1.3s.  That's about 100ms per url() call. I would expect about 1ms to display this value.  This is about 100x slower than it should be IMO.

```twig
{% set propertyDocuments = property.property_documents %}
{% if propertyDocuments|length %}
    {% for document in propertyDocuments %}
        <a href="{{ document.url() }}">{{ document.url() }}</a>
    {% endfor %}
{% endif %}
```

**Comment by Piterden** [comment]
What back-end software do you use?

**Comment by mattcdavis1** [comment]
Not sure what you mean by back-end software but the disk has an S3 source which may be a factor.

**Comment by Piterden** [comment]
I meant​, that Pyro shows much worse performance, if you would use Apache, instead of Nginx.
If you are using S3, I am, actually not surprised about your problem. You could try to mount into any folder of your OS, any remote source. Then just open that folder in any editor, for example ST3. You would feel how it slows down your performance. That's why I'm always using local clone of remote project tree for work.

**Comment by RyanThompson** [comment]
Looking at how this is generated I am VERY surprised about how slow this is. It should be very fast cause the base_url is already set and all it's doing it `base_url + path` and returning it. Base_path is set when the storage adapter is created on load. Which leads me to believe it's response time from S3. 

Closing this for now cause logically it appears outside of Pyro but if you've got more material for me to look over let me know and we can dig in further.
