### ISSUE TITLE
[feature] [accelerant-theme] Make an option for disable hoverable menu mode!!!

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4430]
Ryan, I don't know who tell you about annoying him by hoverable menu, but I tested it with about 20 people. There were people of different professions, men and women. I wouldn't write this issue, if at least one person would told me that your variant is more useful and convenient.
No one didn't tell me that.
Now I'm sure that hoverable menu should be the *default behavior*!!!, and your variant with double-control press, user should be able enable somewhere in the settings.

**Comment by ghost** [comment]
What menu are we talking about here?

**Comment by Piterden** [comment]
I mean that menu
![output](https://user-images.githubusercontent.com/5930429/27836699-47efdba0-60e9-11e7-9c36-a6c771af2b96.gif)

**Comment by ghost** [comment]
Personally, i still like the click.

However, i think this menu is one of the less good UX of the theme. I suggest:

1. I want to get rid of the icons. Admins not using this everyday (even me) forgets what they stand for so i still have to click to view the full name. So show the full item name as per default.
2. I would like all items to be loaded on every request instead of having to click to load em into view.

Then we have the search bar. Which almost eliminate the need of this first layer. 

This is from the top of my head. But i do think we should come up with a better menu. But i don't like the hover myself. 

Last.. Is it really important? Or should ryan maybe fix some other stuff first. We could simply extend the theme and add hover control ourselves..

/w

**Comment by Piterden** [comment]
I don't understand how could I simply extend theme for it, if I don't want to loose updates.

My proposal, from the very beginning of this speech, was to make an option in settings and preferences modules, which would toggle the behaviour.

Search in menu with input at the top is the thing I don't understand.

@designbywilliam what you mean under 2? What items do not load on every request?

**Comment by ghost** [comment]
Syncing?

@Piterden Sub menu items. In your example above, only pages submenu is visible on hover/click. I would like to see all level 2 menu items visible. It would be a lot faster to navigate if all those were always accessible.

**Comment by Piterden** [comment]
Oh, I got it now. Even don't know what would be more useful, need to test your variant. Do you have the working example?

**Comment by ghost** [comment]
@Piterden no.. haven't come so far:) I sort of hit the wall so i have to rest:)

**Comment by Piterden** [comment]
@designbywilliam Rest in peace
