### ISSUE TITLE
[image-field_type] Able to use animated gifs

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4439]
We have an issue since we are not able to use animated gifs since intervention can't handle it. Any ideas @RyanThompson how to best solve this? One idea is obv to just copy the file if it has the gif extension.

**Comment by Piterden** [comment]
I think it would be hard to implement

**Comment by RyanThompson** [comment]
I've added `copy` as an "alteration" type flag.

`{{ img('local://images/example-gif.gif').copy.path }}`

Or like `{{ img('local://images/example-gif.gif').copy|raw }}`

**Comment by designbywilliam** [comment]
I don't understand @RyanThompson . Is the scenario : 
1) The user selects the image with image field type?  or 2) The user select an image using the file field type?

Or how / when is this to be used? Because i am guessing if its with the file field type, i dont understand how to use it. 

Or are you saying that if i upload a gif to files. I can use .copy when referencing the image to skip intervention? But that might be unnecessary since you do that file File anyway...?

**Comment by Piterden** [comment]
:trollface:

**Comment by RyanThompson** [comment]
😚

**Comment by ghost** [comment]
go screw a dog
