### ISSUE TITLE
[Files and Images FTs] Ability to resize and for jpegs, set Quality level on upload.

### ISSUE THREAD

**Issue by ikoniqoz** [pyrocms/pyrocms#4475]
In Good Ol' Pyro 2 we were able to resize image files on upload. What was lacking there was ability to set a Quality level for JPEGs.   It would be a welcome feature set to include resize and quality level on the Files and Image Field Types  on Pyro 3.x

**Comment by calebsmithdev** [comment]
You can do a `resize()` now in twig using this: http://image.intervention.io/api/resize

And then `encode()` for quality and extension changing: http://image.intervention.io/api/encode

IMO - I don't think it's necessary to worry about that on upload since I could use the same image in different places and control them using those presenters.

**Comment by RyanThompson** [comment]
Related to another issue (too lazy to tag) but this is on the roadmap!
