### ISSUE TITLE
[files-field_type] Add all images when uploading

### ISSUE THREAD

**Issue by RienMoeyaert** [pyrocms/pyrocms#4568]
We’re using the images upload to have a images gallery.

An admin can upload 50 images in bulk, but is supposed to click ‘add’ for every one of those 50 images.

This is quite a hassle. Is there a way to have this happen in one move? Upload and auto select?

A useful solution would be an 'add all' button, rather than having to click 'add' for every uploaded item.

**Comment by ThinkGraphical** [comment]
Any update on this?

**Comment by Pixney-William** [comment]
I totally see the use of this feature too. @RyanThompson ?

**Comment by ThinkGraphical** [comment]
To take it a step further, my thought process on this is:
When a user uploads images through the field-type, surely the intent is to add those images to that field, otherwise the user would have just uploaded the images globally through the files module.

So why ask to select them? Sure, the 'Add all' is a valuable solution.. but directly adding the images without the extra modal would improve the UX flow even more.

For example:
Photographer website with an "album" stream.
When they create a new album, they fill in the album name.
Next, they click "upload images"... select the specific images they want in that album (in the native file system), then are presented a modal to manually select the 50 or so images they just specified.

The first thing my girlfriend asked when I showed her how to create an album:
"Why do I have to click 'add' all the images I've just specified before?"

**Comment by Pixney-William** [comment]
Totally agree with your line of thinking here @ThinkGraphical . But i am thinking, maybe we should create another field type instead of changing the files one?

Because maybe, we would like a files field type that just has a drop/select area (you know, dropzoneish). If im not mistaken a guy on slack Oimken was doing something similar to this. Just recently. Ill ask him to join in here.

The reason i say we could do a new one, is because i don't even want to click the upload button. I would just like a drop area to appear and then drop my files there and i am done. WIth a delete button on each one being able to remove them.

Now question is, do you see any issues/problems one would run into creating such a field type @RyanThompson if it Oimken hasn't already sorted a lot of this.

**Comment by oimken** [comment]
Yes，I make a draft image upload field-type call it user_files-field_type, no thing fancy, it just a little modified the `anomaly.field_type.files. for front end user.   All credit is Ryan's, I just did:
1. in config, specify a folder for user upload, limit the how many file per user(in this folder), how many dropzone area..
2. I think the most improvement  is I just show all dropzone area for user drop/clickToSelect their files directly to upload. that is easy for front user using.   of course， user can select the file by click a button to show a modal  with all his own images in it to choose (just  `created_by_id` = user's id ),
3. a little js and css ... 

I want to share it, but it just damn simple(most is Ryan‘s code as I said before), I think everybody can do better  than me in no time after knowns  what it did ..  after all, I am a amateur, Php and js code is too shitty that I shame to show to you guys...

**Comment by Pixney-William** [comment]
@oimken Hey, why dont you just put it out there and we can all chip in on it?

**Comment by RyanThompson** [comment]
We'll get this in there. Duplicate for: https://github.com/pyrocms/pyrocms/issues/4792
