### ISSUE TITLE
[variables-module] Use variable in scss.

### ISSUE THREAD

**Issue by oimken** [pyrocms/pyrocms#4617]
why we can’t use `Variable Module` in `variables.scss` … 
It doesn't make senses,  and makes variable module less attractive...

Please consider about that, make `Variable Module` even better!

**Comment by Piterden** [comment]
SCSS and Twig shouldn't be used together

**Comment by RyanThompson** [comment]
So reviewing some of my code - @Piterden is right and I had thought around this:

Every theme supports a `config/variables.php` file that get's loaded in as `key -> value` variables for the compilers. 

It's powered by the config repository so consider the following example:

```php
<?php

return [
    'example' => '#fallbackcolor',
];
```

Then in your service provider for the theme:

```php
$config->set('anomaly.theme.example::variables.example', $settings->getValue('something'));
```

That will effectively override that value since we're setting it as some different value during runtime.

Now you can use `$example` in your `SCSS` for example. Or `@example` in `LESS`.. whatever your compiler of choice there is.
