### ISSUE TITLE
[files-module] SVG files get interpreted incorrectly + cannot be filtered

### ISSUE THREAD

**Issue by lachieh** [pyrocms/pyrocms#4624]
Some SVG files get interpreted as `text/html` and some as `image/svg+xml`.

Adding 'svg' to the 'Allowed Types' field on the Folder does not allow for either to be uploaded. The Javascript alert() error is "The file must be a file of type: svg".

[example_svgs.zip](https://github.com/pyrocms/pyrocms/files/1352817/example_svgs.zip)

**Comment by RyanThompson** [comment]
So I have been doing some research on this and I don't think this is something we should account for. I would suggest opening up your folder by adding those mimes to the allowed types list.

Reason being is it is a very slippery slope. If we add an exception for text/html when the file extension is SVG that can potentially be a security issue I think. Simply because we're ignoring the mimes. 

Does this make sense?

Whereas you can add `text/html` and `image/svg+xml` to your allowed types and now you know what to expect.

**Comment by RyanThompson** [comment]
I could see maybe adding the mime type to the error response that would be nice. So you can quickly add it to allowed types.

**Comment by RyanThompson** [comment]
In 2.2 we had a map of mimes per type.. but it was exhausting - that's what Laravel does for us now. Seems like to me the easiest way forward is just adding those mimes to your allowed list :-/

**Comment by lachieh** [comment]
That's the problem though, you can't enter `image/svg+xml` into the 'Allowed Types' list.

Before saving:
![before-save](https://user-images.githubusercontent.com/1687902/31229929-53b2e468-a9b0-11e7-8729-d445a80bdbb7.png)

After saving:
![after-save](https://user-images.githubusercontent.com/1687902/31229944-5e2db576-a9b0-11e7-81f8-664cbc29e177.png)

**Comment by RyanThompson** [comment]
That - I can fix!

**Comment by Piterden** [comment]
Extension is not a mime type, isn't it?

**Comment by lachieh** [comment]
Nah mime type is detected from the contents of the file. Not really sure how, but it's a Laravel thing, right @ryanthompson?

**Comment by Piterden** [comment]
I added just `svg` and everything worked for me

**Comment by RyanThompson** [comment]
Same here and I know Laravel has mime adjustment configurations too
