### ISSUE TITLE
[Twig / Assetics bug] Unclosed Comment issue needs to be fixed

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4659]
This is regarding the issue when compiling sass code we spoke of earlier. It throws a `Unclosed comment` dump.

The cause is that compressed css may look like this: `{#vlog-search-result`

And then it interpret that as a twig comment.

**Comment by Piterden** [comment]
I don't believe you.

**Comment by Piterden** [comment]
??? @designbywilliam

**Comment by Pixney-William** [comment]
@RyanThompson is this something that would be very time consuming for you?

**Comment by Pixney-William** [comment]
@RyanThompson have you had time looking into this issue yet? Bugs me:)

**Comment by Pixney-William** [comment]
So this is obviously still existing. I could close it, because we are a limited amount of people working this way. Well, actually i don't know how limited group it is, since it's growing. At the same time, it feels like something that shouldn't exist.

Let me know what you feel and i could close it if you want - @RyanThompson

**Comment by Eighke** [comment]
I had it again yesterday (I cannot compile anymore my scss using `npm run prod` I have to `npm run dev`~).

**Comment by Pixney-William** [comment]
@Eighke yes. I also think this is a "problem" . Not critical, but it's annoying for my workflow and the people i work for.
