### ISSUE TITLE
[Bug] Remove Old Session Errors

### ISSUE THREAD

**Issue by mattcdavis1** [pyrocms/pyrocms#4664]
This is the same issue as #4320 (closed). Here is how to reproduce:

1. Save any front-end form with a validation error
2. Load another form without fixing the validation error from the first form.

Result: Validation error from form A shows on form B.

Sample code:

```php
$formBuilder = app(FormBuilder::class)
    ->setEntry($entry);

$formBuilder->make();
$form = $formBuilder->getForm();

return view('theme::my.form', compact('form'))
```

Simple fix: In the construct of the base form builder (or just somewhere early in the script process): `session()->pull('error');` to remove any existing errors from previous forms.

**Comment by Piterden** [comment]
What is `$entry`?

**Comment by mattcdavis1** [comment]
The form entry in edit mode.

```php
public function edit($id)
{
    $entry = app(MyModel::class)->find($id);

    $formBuilder = app(FormBuilder::class)
        ->setEntry($entry);

    $formBuilder->make();
    $form = $formBuilder->getForm();

    $response = $form->getResponse();

    if (!$form->hasErrors() && $response) {
        return redirect()->route('some.route');
    }

    return view('theme::my.form', compact('form'));
}
```

**Comment by Piterden** [comment]
I had a similar issue, when I had the command `AddDocumentForms`, which added forms to the form builder in a loop. That loop was inside handle method of a command.
So all forms became the same after command had worked.
I had remove it then and made another command instead, `AddDocumentForm` 
Now I have the loop outside that new command, like:
```php
        /* @var FormInterface $form */
        foreach ($document->getForms()->all() as $form) {
            $this->dispatch(new AddDocumentForm($builder, $form));
        }
```
And inside command I have:
```php
public function handle(EntryFormBuilder $builder) 
{
        $this->builder->addForm(
            $this->form->getSlug(),
            $builder->setModel($this->form->getEntryModelName())
        );
}
```
Everything works great now. Could it be like so for you?

**Comment by RyanThompson** [comment]
This is an issue I think with flash messages just building up in the bag. Are you intending on not displaying the flash messages but doing some kind of reporting on your own? Outside of the default errors / message bag?

**Comment by mattcdavis1** [comment]
no - the issue is just that the flash messages never get cleared (except for after successfully fixing errors).  At least not with the way i have it setup which afaik is the proper way to handle it in Pyro (the other option of submitting to the default form handler URL doesn't give me enough control).  

So if a person triggers a validation error and then doesn't re-submit the form something in Pyro is continuing to persist the flash message which shouldn't happen.  Flash messages should only ever stick around for the next page load.

**Comment by Piterden** [comment]
Long time ago I had it worked correct, only with this way:
```php
        $params = [
            'messages' => [
                'error'   => $this->messages->get('error'),
                'success' => $this->messages->get('success'),
                'info'    => $this->messages->get('info'),
                'warning' => $this->messages->get('warning'),
            ],
        ];

        $view = view('theme::layouts.default', $params);

        $this->messages->flush();

        return response($view, 200);
```

**Comment by Pixney-William** [comment]
@RyanThompson Is this still a bug?

**Comment by RyanThompson** [comment]
I think this is still a message behavior. I just tested this on a public form - the register one for example. Form errors (required fields). Loaded the form on another tab and they're not there because the session stuff is pulled in the view (usually a messages partial). So they are no longer present. However if your view doesn't get a chance to do this then it's stuffed. 

I think.. form sessions would benefit from being keyed to the form though. Cause if I post a heavy form and pop open to another tab late while it's validating I get session messages from that form spilling over cause they are global - not namespaced or isolated to the form. 

I am confident that if your view was removing those messages in some way (or handling it the form some how if you prefer) the other form will not display the same errors. 

If at some time the session messages were more sticky then that has been fixed at some point. But I think the issue is likely in how they're pulled out for display.
