### ISSUE TITLE
[users-module] Mails send from Example not settings email

### ISSUE THREAD

**Issue by dwainscheeren** [pyrocms/pyrocms#4711]
When I invalidate a password users get mail from Example <example@example.com> instead of name from settings and e-mailadres.

**Comment by adrianfalleiro** [comment]
@dwainscheeren I came across this issue too.

From my investigation, it appears that when `config('app.debug')` is set to true, `MailServiceProvider` is initialised before the PyroCMS addons have loaded. This means that the `config('mail.from')` value is being read directly from the values in the `app/config/mail.php` file and not being overridden by PyroCMS.

Since the `MailServiceProvider` is a deferred provider, ordinarily this wouldn't be an issue - but it looks like the Laravel Debugbar triggers registration of the Mail services before the PyroCMS config/settings override come into effect.

@Piterden @RyanThompson Does the Debugbar need to be registered in the `register()` method of `StreamsServiceProvider`? Its already being re-registered in the 'boot()' method. Removing it from the `register()` method seems to resolve this issue for me.

**Comment by Pixney-William** [comment]
@RyanThompson Comments on this?

**Comment by Pixney-William** [comment]
@dwainscheeren @adrianfalleiro  is this still an issue?

**Comment by RyanThompson** [comment]
Fixed in 3.6: https://github.com/anomalylabs/streams-platform/commit/0160d6928265f13d4142a320dbc6bb9ed5beb571
