### ISSUE TITLE
[redirects-module] possible bug

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4713]
# Works
Redirect From : `events`

# Does not work

Redirects From : `events/exhibitions`
Redirects From : `events/exhibitions/myurl`

**Comment by RyanThompson** [comment]
Is events a module? It's likely due to _when_ these routes are routed (if they are outside of this redirect).

Routes are last come first serve for the most part in Laravel - and this causes issues when multiple addons are trying to route the same thing. 

- Renaming posts for example is a bad use currently for this addon. It's tricky due to internal route conflicts.

- Redirecting OLD routes for a website to new routes is a good example.
- Redirecting SEO routes for a website to pages or something is another good example (pyrocms.com/sale2018 for example)

Neither of those examples are fighting with internal routes. Do note though you can override pages this way (as can pages module override login route n stuff too because they're deferred: https://github.com/pyrocms/pyrocms/blob/3.4/resources/streams/config/addons.php#L31)

**Comment by Pixney-William** [comment]
Correct, events is a module. 

The correct use case here, was that the client had named the url bad from a seo perspective : 
`events/exhibitions/bad-url` and then changed it to : `events/exhibitions/good-url`. And since they had already published the url publically on twitter, we want the bad url to redirect to the good-url.

I get that conflicts would crash things. I just can't figure out where that conflict is though. I have skipped the redirect module right now for this. But i'll try figure this out to make sure we have some more info on the issue.

/W

**Comment by Piterden** [comment]
https://github.com/pyrocms/pyrocms/pull/4716

**Comment by Pixney-William** [comment]
Closing this issue since i guess it's not to be fixed.
