### ISSUE TITLE
[streams-platform] files-field_type is not working  at streams-platform v1.3.95 

### ISSUE THREAD

**Issue by oimken** [pyrocms/pyrocms#4731]
Files-field_type  got error even in core module.

Here is the way to reappear in Page-module:
1. if there is no page type with files-field_type assigned,  create a files-field_type add assign to a page type
2. create a new page with the page type
3. you will got  500, error log will have something like this:
```ErrorException(code: 0): array_filter() expects parameter 1 to be array, null given at ..../core/anomaly/files-field_type/src/FilesFieldType.php:83)```

I think this is a bug, please check it out.

**Comment by robinvoor** [comment]
Got the same error, trying to create a page with the files-field_type returns:
```
An exception has been thrown during the rendering of a template ("An exception has been thrown during the rendering of a template ("An exception has been thrown during the rendering of a template ("array_filter() expects parameter 1 to be array, null given").").").
```

**Comment by theworkfounder** [comment]
The same error, like you!

**Comment by dwainscheeren** [comment]
Got the same error here.

**Comment by robinvoor** [comment]
Alright I was testing other versions of the streams-platform, it appears using version 1.3.92 is not returning any errors anymore and thus I can successfully create a page again. (also used `php artisan assets:clear` and `php artisan cache:clear`)

**Comment by oimken** [comment]
@theworkfounder checked.  Revert this commit will make the error away:
https://github.com/anomalylabs/streams-platform/commit/2c3db2f499b3c5a99059591f793addfa670cd1ef

**Comment by RyanThompson** [comment]
On it

**Comment by RyanThompson** [comment]
Thanks for pointing that out @oimken - huge help!

The null value is required so that translations for non-primary locales can be left blank. So I can't rightly revert the commit. However, this should fix it properly - thanks for the heads up! 

https://github.com/anomalylabs/multiple-field_type/commit/900d803dc79961f79d40037e7c97aa7d2c4cb370
https://github.com/anomalylabs/files-field_type/commit/2d104c004a2fe43dfc209dd6a0728ed85fd23167
