### ISSUE TITLE
[multiple field type] Multiple Field Type with lookup mode not working in Stream (1.3.95)

### ISSUE THREAD

**Issue by theworkfounder** [pyrocms/pyrocms#4732]
When i assign a field type with lookup mode to a stream, it generate error like this:
`Argument 1 passed to Anomaly\MultipleFieldType\Table\ValueTableBuilder::setSelected() must be of the type array, null given, called in ...core/anomaly/multiple-field_type/src/MultipleFieldType.php on line ...`
PS: Only with lookup mode, tag mode work normal.

**Comment by Dinushasilva** [comment]
Same issue, only appears to have when creating a new entry.

**Comment by theworkfounder** [comment]
@Dinushasilva 
Quick fix: downgrade to stream platform: 1.3.92 and wait for update!

**Comment by RyanThompson** [comment]
The null value is required so that translations for non-primary locales can be left blank. So I can't rightly revert the commit. However, this should fix it properly - thanks for the heads up! 

https://github.com/anomalylabs/multiple-field_type/commit/900d803dc79961f79d40037e7c97aa7d2c4cb370
https://github.com/anomalylabs/files-field_type/commit/2d104c004a2fe43dfc209dd6a0728ed85fd23167
