### ISSUE TITLE
Pyrocms throwing this error: 21 bad parameter or other API misuse

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4867]
**Describe the bug**
When using PyroCMS 3.5 i am getting (and others) these errors. For me hit happens randomly, meaning it's hard to locate when and where it happens. Googling seems to point to teamtnt (https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/129).

What are we going to do? Downgrade teamtnt? Downgrade php version?

**To Reproduce**
Good luck!

**Video**
https://streamable.com/h7eer

**Screenshots**
![image](https://user-images.githubusercontent.com/31292231/48663531-f10b3080-ea91-11e8-8622-12ce9b4a986f.png)

![image](https://user-images.githubusercontent.com/31292231/48663538-fb2d2f00-ea91-11e8-8740-f99ee5b038e0.png)

**Desktop (please complete the following information):**
- Pyrocms 3.5
- Php 7.2

**Comment by Pixney-William** [comment]
This issue occur both in public and in admin.

**Comment by Eighke** [comment]
I currently downgraded my PHP to 7.1, but we really need to fix teamtnt :/

**Comment by mmodler** [comment]
Its really annoying - not using php 7.2 is not an option for us :(

**Comment by biggins** [comment]
Just an update on this, I have tested on PHP7.2 using the tntsearch master branch using:
`"teamtnt/tntsearch" : "dev-master as 1.0.7"` in my composer.json and it has fixed the issue for me, since they made this update https://github.com/teamtnt/tntsearch/pull/126/commits/6ced58c7cfcc9a23ed8ea3481f43bb4f884107b0 

tntsearch master branch has been tagged as v1.4.0 but streams-platform is locked to use 1.0.x but the dependency on `"teamtnt/laravel-scout-tntsearch-driver": "3.0.4"` I assume this could be updated here https://github.com/anomalylabs/streams-platform/blob/1.5/composer.json#L29 @RyanThompson?
 
Happy to put in a PR but wanted to check it isn't locked for a reason?

**Comment by mmodler** [comment]
I remember the lock was because the tnt guys messed up everything some versions ago.
@RyanThompson If it works with current versions, the lock can be updated/removed?

**Comment by RyanThompson** [comment]
This is fixed in 3.7 and can be used now in the streams platform 1.6 dev branch using `1.6.x-dev` to confirm / test.
