### ISSUE TITLE
Addon constantly requires internet connection?

### ISSUE THREAD

**Issue by ghost** [pyrocms/pyrocms#4875]
Installed pyrocms on local xampp server but when i click the addon icon(admin dashboard) got this error in offline:

**_ErrorException (E_WARNING)
file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known._**

Arguments:

"file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known. "

**Comment by RyanThompson** [comment]
What is it asking for? I use offline all the time and never have any issues.

If you're trying to download or cache assets from a remote source though you might get something like this (file_get_contents is typically done in assets). 

Also it might be requesting local assets but being treated as remote due to environment setup.
