### ISSUE TITLE
Input entry for different languages is not working in front-end

### ISSUE THREAD

**Issue by fatihalp** [pyrocms/pyrocms#4905]
**Describe the bug**

In admin panel translations is working well. In our module we tried days to implements multi language feature to front-end. Couldn't make it work. Just checked for posts module and default theme, also there isn't working.

**To Reproduce**
1- Add translatable to posts module.
2- Add form with  {{ form('todo','todo')|raw }} in view/twig
3- Check language switcher is working or not?

**Expected behavior**
should save data in Both languages. But even switcher is not working. 

**Screenshots**

![image](https://user-images.githubusercontent.com/219454/51751987-4fbedd00-20c7-11e9-994f-ac0eef15c527.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chromium
 - Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by RyanThompson** [comment]
Hmm these forms aren't really designed for the front end. However you can take a look at https://github.com/anomalylabs/streams-platform/blob/1.5/resources/js/form/translations.js

First see if it's getting pulled in in the front end. Then if so - maybe it can be made to work both ways otherwise copy it and include it yourself in your theme for your front end form and modify as needed.

**Comment by emeksancar** [comment]
What's the intended method for custom front-end forms then?
