### ISSUE TITLE
[Core : Versioning] Versions are saved, but not retrieved.

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4950]
**Describe the bug**
Versions seem to be stored to the database. It also works to retrieve normal page data as title, description from versions.

But if you for example attach a grid field type with a versionable grid (in this case a markdown field type) you can not load a version and see that data in the textarea (markdownarea).

**To Reproduce**
* Go to grids, create a grid, make it versionable, attach a markdown field type
* Attach the a grid to a page and use the markdown grid and write something in the textarea. save the page.
* Repeat once or twice.
* Now try to load a previous version. If you have changed title and description, you will see that being populated. However, the grid field stays, and no previous data is added here.

**Data is saved however**
![image](https://user-images.githubusercontent.com/31292231/55816221-160c4880-5af2-11e9-9a0e-86a153cba5e1.png)

**VIDEO**

https://streamable.com/a3jr6

**Comment by rmondesilva** [comment]
I am experiencing this issue too. 

`get_class() expects parameter 1 to be object, null given` shows up on PHP 7.2, changing to PHP 7.0 hides the error but no changes happen, because the `$this->form->getModel()` is still null. 

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/18656034/56865963-a1e50680-6a06-11e9-88bd-cc0c0b42398d.png">

I agree that changes on Title or Description (those original fields) are the only ones that is really saving the version changes. 

When you load it, it loads up. 

But after you save it, it returns back to the current one.

**Comment by Pixney-William** [comment]
Also this:

https://github.com/pyrocms/pyrocms/issues/4974

**Comment by fatihalp** [comment]
Ryan says that issue is solved #4974
