### ISSUE TITLE
[search-module] no support for exact phrase searching

### ISSUE THREAD

**Issue by TheBeems** [pyrocms/pyrocms#5038]
**Describe the bug**
When searching an exact phrase with double quotes, the following error occurs: 

> An exception has been thrown during the rendering of a template ("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'plato"*") >= ? or MATCH (searchable) AGAINST ("+"plato"*") >= ? or `title` LIKE ' at line 1 (SQL: select * from `default_search_items` where `locale` = nl and MATCH (title,description) AGAINST ("+"plato"*") >= 3 or MATCH (searchable) AGAINST ("+"plato"*") >= 3 or `title` LIKE %"plato"% or `description` LIKE %"plato"% order by MATCH (title,description) AGAINST ("+"plato"*") desc, MATCH (searchable) AGAINST ("+"plato"*") desc)").

**To Reproduce**
Do a search between double quotes, e.g. "plato".

**Expected behavior**
Searching the exact phrase that is placed between double quotes as described in [the docs](https://dev.mysql.com/doc/refman/5.5/en/fulltext-natural-language.html).

**Comment by RyanThompson** [comment]
I tend to agree - but this is going to be related to this scout driver specifically instead of the search system as a whole. Reason being is because scout is the underlying system and whatever we support needs to either occur above scout or be supported by scout. 

In the meanwhile - I've added literal searching so `plato` will check for literal (boolean) matches but it's all returned at once right now. Will revisit this.
