### ISSUE TITLE
Composer 2 and PHP 8 install error 3.8

### ISSUE THREAD

**Issue by jgulledge19** [pyrocms/pyrocms#5099]
**Describe the bug**
I have PHP 8 and Composer 2 running on my Mac and tried to do a simple install to try out PyroCMS. Composer gives an error message:

**To Reproduce**
1. Run the composer command in the terminal: `composer create-project pyrocms/pyrocms` 

**Expected behavior**
Install PyroCMS package requirements. 

**Screenshots**
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/671767/111167725-c5bc8180-8577-11eb-9613-2cbd387b809e.png">

**Additional context**
Looks like the `wikimedia/composer-merge-plugin` package needs to be updated to version 2: https://github.com/wikimedia/composer-merge-plugin#upgrading-from-composer1-to2

Related to #5070

**Comment by b1gw0rm** [comment]
I'm having the same issue with composer 2 not being compatible with the two packages wikimedia/composer-merge-plugin and also anomaly/streams-composer-plugin due to them both having composer 1 as a specific dependency and so I'm trying to come up with workarounds in the meantime.

The biggest issue for me on this one is the wikimedia/composer-merge-plugin because that's how Pyro sees what templates you have in the addons folder so we have errors with adding new templates because composer will just ignore that plugin completely and so composer dump-autoload does nothing.

A temporary workaround might be to find a composer.phar file that is still 1.x version and use that like "php composer.phar update" from the command line.

**Comment by edster** [comment]
This is fixed in 3.9

**Comment by b1gw0rm** [comment]
That's good to know. I see that there is an upgrade guide for anybody looking:

https://pyrocms.com/documentation/pyrocms/3.9/prologue/upgrade-guide
